/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateReceiptRouteImport } from './routes/create-receipt'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as ReceiptsReceiptIdRouteImport } from './routes/receipts.$receiptId'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateReceiptRoute = CreateReceiptRouteImport.update({
  id: '/create-receipt',
  path: '/create-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReceiptIdRoute = ReceiptsReceiptIdRouteImport.update({
  id: '/receipts/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/receipts': typeof ReceiptsIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-receipt'
    | '/receipts/$receiptId'
    | '/students/$studentId'
    | '/receipts/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-receipt'
    | '/receipts/$receiptId'
    | '/students/$studentId'
    | '/receipts'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/create-receipt'
    | '/receipts/$receiptId'
    | '/students/$studentId'
    | '/receipts/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateReceiptRoute: typeof CreateReceiptRoute
  ReceiptsReceiptIdRoute: typeof ReceiptsReceiptIdRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-receipt': {
      id: '/create-receipt'
      path: '/create-receipt'
      fullPath: '/create-receipt'
      preLoaderRoute: typeof CreateReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$receiptId': {
      id: '/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof ReceiptsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateReceiptRoute: CreateReceiptRoute,
  ReceiptsReceiptIdRoute: ReceiptsReceiptIdRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
