/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateReceiptRouteImport } from './routes/create-receipt'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as ReceiptsReceiptIdRouteImport } from './routes/receipts.$receiptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateReceiptRoute = CreateReceiptRouteImport.update({
  id: '/create-receipt',
  path: '/create-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReceiptIdRoute = ReceiptsReceiptIdRouteImport.update({
  id: '/receipts/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/receipts/': typeof ReceiptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/receipts': typeof ReceiptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/receipts/': typeof ReceiptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-receipt' | '/receipts/$receiptId' | '/receipts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-receipt' | '/receipts/$receiptId' | '/receipts'
  id:
    '__root__' | '/' | '/create-receipt' | '/receipts/$receiptId' | '/receipts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateReceiptRoute: typeof CreateReceiptRoute
  ReceiptsReceiptIdRoute: typeof ReceiptsReceiptIdRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-receipt': {
      id: '/create-receipt'
      path: '/create-receipt'
      fullPath: '/create-receipt'
      preLoaderRoute: typeof CreateReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$receiptId': {
      id: '/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof ReceiptsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateReceiptRoute: CreateReceiptRoute,
  ReceiptsReceiptIdRoute: ReceiptsReceiptIdRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
