/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CreateReceiptRouteImport } from './routes/create-receipt'
import { Route as DurationsRouteImport } from './routes/durations'
import { Route as ProgramTypesRouteImport } from './routes/program-types'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as ReceiptsReceiptIdRouteImport } from './routes/receipts.$receiptId'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateReceiptRoute = CreateReceiptRouteImport.update({
  id: '/create-receipt',
  path: '/create-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const DurationsRoute = DurationsRouteImport.update({
  id: '/durations',
  path: '/durations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramTypesRoute = ProgramTypesRouteImport.update({
  id: '/program-types',
  path: '/program-types',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReceiptIdRoute = ReceiptsReceiptIdRouteImport.update({
  id: '/receipts/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/durations': typeof DurationsRoute
  '/program-types': typeof ProgramTypesRoute
  '/settings': typeof SettingsRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/durations': typeof DurationsRoute
  '/program-types': typeof ProgramTypesRoute
  '/settings': typeof SettingsRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/receipts': typeof ReceiptsIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/create-receipt': typeof CreateReceiptRoute
  '/durations': typeof DurationsRoute
  '/program-types': typeof ProgramTypesRoute
  '/settings': typeof SettingsRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/create-receipt'
    | '/durations'
    | '/program-types'
    | '/settings'
    | '/receipts/$receiptId'
    | '/students/$studentId'
    | '/receipts/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/create-receipt'
    | '/durations'
    | '/program-types'
    | '/settings'
    | '/receipts/$receiptId'
    | '/students/$studentId'
    | '/receipts'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/create-receipt'
    | '/durations'
    | '/program-types'
    | '/settings'
    | '/receipts/$receiptId'
    | '/students/$studentId'
    | '/receipts/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRoute
  CreateReceiptRoute: typeof CreateReceiptRoute
  DurationsRoute: typeof DurationsRoute
  ProgramTypesRoute: typeof ProgramTypesRoute
  SettingsRoute: typeof SettingsRoute
  ReceiptsReceiptIdRoute: typeof ReceiptsReceiptIdRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-receipt': {
      id: '/create-receipt'
      path: '/create-receipt'
      fullPath: '/create-receipt'
      preLoaderRoute: typeof CreateReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/durations': {
      id: '/durations'
      path: '/durations'
      fullPath: '/durations'
      preLoaderRoute: typeof DurationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-types': {
      id: '/program-types'
      path: '/program-types'
      fullPath: '/program-types'
      preLoaderRoute: typeof ProgramTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$receiptId': {
      id: '/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof ReceiptsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRoute,
  CreateReceiptRoute: CreateReceiptRoute,
  DurationsRoute: DurationsRoute,
  ProgramTypesRoute: ProgramTypesRoute,
  SettingsRoute: SettingsRoute,
  ReceiptsReceiptIdRoute: ReceiptsReceiptIdRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
